Fix an issue with describe blocks with matching names
pestphp/pest pull request #1304
Opened 2024-10-22 15:03 UTC by jshayes

### What:

- [x] Bug Fix
- [ ] New Feature

### Description:

Fixes an issue described here: https://github.com/pestphp/pest/pull/1295#issuecomment-2409008790

The issue is caused by using the describe block name to determine if a `beforeEach`, or similar hook, should be applied. This PR wraps the description in an object so that the strict equal check will only pass when the hook is applied to the same describe block, not just a describe block with the same name.

### Related:

https://github.com/pestphp/pest/pull/1295#issuecomment-2409008790

2024-11-10 15:29 UTC, nunomaduro requested changes

2024-11-10 15:29 UTC, nunomaduro commented on src/PendingCalls/DescribeCall.php
> +        string $description,
can you accept an `public readonly Description $description` here?

2025-01-05 16:41 UTC, JeffBeltran commented
ran into something similar this this weekend after upgrading to v3 and started using nested describe blocks. would love to see this merged in

2025-05-29 08:58 UTC, zillemarco commented
I ran into exactly this today 😅 Is this planned to be picked up/merged any time soon @nunomaduro ? 🙂

2025-07-26 03:26 UTC, merged