Add name to description for named datasets
pestphp/pest pull request #134
Opened 2020-07-19 10:30 UTC by sshead

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | 

With named datasets, Pest does not currently include the dataset name in test output. This PR inserts the dataset name in the dataset description, so that the output of both the test result and failure messages mimic the PHPUnit format.

For example, given the test:

```
test('same pest style', function ($val) {
    $this->assertSame(1, $val);
})->with([
    'one' => [1],
    'two' => [2],
]);
```

the current output includes:
```
  ✓ same with (1)
  ⨯ same with (2)

  ---

  • Tests\Unit\Datasets > same with (2)
```

With this PR, the new output is:

```
  ✓ same with data set "one" (1)
  ⨯ same with data set "two" (2)

  ---

  • Tests\Unit\Datasets > same with data set "two" (2)
```

The PHPUnit failure output, for a test equivalent to the above, is:

```
1) DatasetsTest::testSame with data set "two" (2)
```

2020-07-19 11:15 UTC, sshead commented
Hmm... With the data, it can make for very long output lines - which you don't care about much if the test passed. But if a test fails, it's nice to see the data that failed, not just the name, in the context of the test suite output. And "only sometimes" would be a bigger refactor.

2020-07-19 11:32 UTC, owenvoke commented
Fair enough, that's fine. :+1: All good in my opinion.

2020-09-22 20:58 UTC, nunomaduro requested changes
@sshead Can you rebase this pull request? Also, can you add a test that actually uses the feature and prints the output to the snapshot?

2020-09-30 06:19 UTC, sshead commented
Let me know if this wasn't what you were after, or if there's anything else I need to do. (I'm such a part-time "not my day job" dev that this is the first time I've ever force-pushed ... hope I didn't break the world 😅)

2020-09-30 18:50 UTC, nunomaduro approved these changes
Sounds good to me, just left a comment.

2020-09-30 18:50 UTC, nunomaduro commented on tests/Unit/Datasets.php
> +    $this->assertSame('test description with data set "one" (1)', $descriptions[0]);
Can you use the expectation API here?

2020-10-01 04:13 UTC, sshead commented on tests/Unit/Datasets.php
> +    $this->assertSame('test description with data set "one" (1)', $descriptions[0]);
Done.

2020-10-01 08:03 UTC, nunomaduro approved these changes
This is ready to merge and tag.

2020-10-01 08:03 UTC, nunomaduro commented
@sshead Congrats, great contribution.

2020-10-03 15:39 UTC, merged