[2.x] feat(parallel): Adds support for plugins to filter parallel arguments
pestphp/pest pull request #703
Opened 2023-03-20 11:28 UTC by lukeraymonddowning

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| Fixed tickets | #682

Basically, `CallsHandlesArguments` is not executed fully in parallel (and rightly so). However, this means that plugins have no way of altering arguments and thus supporting parallel execution.

This PR adds a new action and contract that allows plugins to alter parallel arguments before parallel execution.

2023-03-21 12:39 UTC, owenvoke commented
@lukeraymonddowning, I still don't think that this resolves the issue... 🤔 Unless I'm implementing the contract wrongly, it seems to have stripped the `--gql-coverage` flag before it even gets to the plugin.

2023-03-21 21:09 UTC, nunomaduro requested changes

2023-03-21 21:09 UTC, nunomaduro commented on src/Contracts/Plugins/HandlesParallelArguments.php
> +interface HandlesParallelArguments
Wondering it this shouldn't be `HandlesParallelWorkerArguments`?

2023-03-22 11:31 UTC, owenvoke approved these changes

2023-03-24 11:22 UTC, merged