[2.x] Add `toBeUUID` expectation
pestphp/pest pull request #948
Opened 2023-09-05 01:27 UTC by hungthai1401

### What:

- [ ] Bug Fix
- [x] New Feature

### Description:

This PR adds `toBeUUID` expectation.

Usage:

```php
expect('00112233-4455-8677-8899-aabbccddeeff')->toBeUUID();
```

### Related:

2023-09-05 20:15 UTC, devajmeireles approved these changes
Thanks for your PR.

2023-09-05 22:17 UTC, nexxai commented
I have a decent amount of experience with UUIDs and this all look decent to me.  I can't think of any edge cases that this regex wouldn't catch off the top of my head.

2023-09-05 22:20 UTC, nunomaduro requested changes

2023-09-05 22:20 UTC, nunomaduro commented on src/Mixins/Expectation.php
> +    public function toBeUUID(string $message = ''): self
```suggestion
    public function toBeUuid(string $message = ''): self
```

2023-09-05 22:51 UTC, inxilpro commented
I believe a slightly better regex would be:

`/^(?:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}|00000000-0000-0000-0000-000000000000)$/iD`

This accounts for known versions (1–5) and variants (8, 9, a, or b), while still allowing the NIL UUID. 

This pattern comes from [uuidjs](https://github.com/uuidjs/uuid)

2023-09-06 01:25 UTC, hungthai1401 commented
@inxilpro I think the current regex is good. This regex pattern comes from [laravel](https://github.com/laravel/framework/blob/52b301797d7a229bf7ebd3e2eefc762487738578/src/Illuminate/Support/Str.php#L519)

2023-09-06 02:10 UTC, gabbanaesteban commented
There are different versions of UUIDs.

I would suggest using the approach used by https://www.npmjs.com/package/validator

Here is the validation https://github.com/validatorjs/validator.js/blob/master/src/lib/isUUID.js

2023-09-06 10:53 UTC, nunomaduro approved these changes

2023-09-06 10:54 UTC, merged

2023-09-06 10:55 UTC, nunomaduro commented
@nexxai Can you PR docs?

2023-09-06 11:06 UTC, hungthai1401 commented
@nunomaduro I've created the documentation related to that: https://github.com/pestphp/docs/pull/229